// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package database

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO
	links (url, hash)
VALUES
	($1, $2) RETURNING id,
	created_at,
	updated_at,
	deleted_at,
	url,
	hash
`

type CreateLinkParams struct {
	Url  string `json:"url"`
	Hash string `json:"hash"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Url, arg.Hash)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Url,
		&i.Hash,
	)
	return i, err
}

const getLinkByHash = `-- name: GetLinkByHash :one
SELECT
	id,
	created_at,
	updated_at,
	deleted_at,
	url,
	hash
FROM
	links
WHERE
	hash = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetLinkByHash(ctx context.Context, hash string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByHash, hash)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Url,
		&i.Hash,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
	id,
	created_at,
	updated_at,
	deleted_at,
	url,
	hash
FROM
	links
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Url,
		&i.Hash,
	)
	return i, err
}

const hardDeleteLink = `-- name: HardDeleteLink :execrows
DELETE FROM
	links
WHERE
	id = $1
`

func (q *Queries) HardDeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLinks = `-- name: ListLinks :many
SELECT
	id,
	created_at,
	updated_at,
	deleted_at,
	url,
	hash
FROM
	links
WHERE
	deleted_at IS NULL
ORDER BY
	id DESC
LIMIT
	$2 :: integer OFFSET $1 :: integer
`

type ListLinksParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Url,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLink = `-- name: RestoreLink :execrows
UPDATE
	links
SET
	deleted_at = NULL,
	updated_at = now()
WHERE
	id = $1
	AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteLink = `-- name: SoftDeleteLink :execrows
UPDATE
	links
SET
	deleted_at = now(),
	updated_at = now()
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLinkURL = `-- name: UpdateLinkURL :one
UPDATE
	links
SET
	url = $1,
	updated_at = now()
WHERE
	id = $2
	AND deleted_at IS NULL RETURNING id,
	created_at,
	updated_at,
	deleted_at,
	url,
	hash
`

type UpdateLinkURLParams struct {
	Url string `json:"url"`
	ID  int64  `json:"id"`
}

func (q *Queries) UpdateLinkURL(ctx context.Context, arg UpdateLinkURLParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkURL, arg.Url, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Url,
		&i.Hash,
	)
	return i, err
}
