// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO
  links (
    user_id,
    url,
    hash,
    title,
    expires_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5
  ) RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type CreateLinkParams struct {
	UserID    int64              `json:"user_id"`
	Url       string             `json:"url"`
	Hash      string             `json:"hash"`
	Title     pgtype.Text        `json:"title"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Url,
		arg.Hash,
		arg.Title,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByHash = `-- name: GetLinkByHash :one
SELECT
  id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
FROM
  links
WHERE
  hash = $1
  AND deleted_at IS NULL
  AND is_active = true
  AND (
    expires_at IS NULL
    OR expires_at > now()
  )
`

func (q *Queries) GetLinkByHash(ctx context.Context, hash string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByHash, hash)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
  id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
FROM
  links
WHERE
  id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetLinkByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetLinkByID(ctx context.Context, arg GetLinkByIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByPublicID = `-- name: GetLinkByPublicID :one
SELECT
  id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
FROM
  links
WHERE
  public_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetLinkByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetLinkByPublicID(ctx context.Context, arg GetLinkByPublicIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByPublicID, arg.PublicID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteLink = `-- name: HardDeleteLink :one
DELETE FROM
  links
WHERE
  public_id = $1
  AND user_id = $2 RETURNING id
`

type HardDeleteLinkParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) HardDeleteLink(ctx context.Context, arg HardDeleteLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, hardDeleteLink, arg.PublicID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLinksByUser = `-- name: ListLinksByUser :many
SELECT
  id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
FROM
  links
WHERE
  user_id = $1
  AND deleted_at IS NULL
ORDER BY
  created_at DESC,
  id DESC
LIMIT
  $3 :: integer OFFSET $2 :: integer
`

type ListLinksByUserParams struct {
	UserID     int64 `json:"user_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListLinksByUser(ctx context.Context, arg ListLinksByUserParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksByUser, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Url,
			&i.Hash,
			&i.Title,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLink = `-- name: RestoreLink :one
UPDATE
  links
SET
  deleted_at = NULL,
  updated_at = now()
WHERE
  public_id = $1
  AND user_id = $2
  AND deleted_at IS NOT NULL RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type RestoreLinkParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) RestoreLink(ctx context.Context, arg RestoreLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, restoreLink, arg.PublicID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setLinkActive = `-- name: SetLinkActive :one
UPDATE
  links
SET
  is_active = $1,
  updated_at = now()
WHERE
  public_id = $2
  AND user_id = $3
  AND deleted_at IS NULL RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type SetLinkActiveParams struct {
	IsActive bool        `json:"is_active"`
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) SetLinkActive(ctx context.Context, arg SetLinkActiveParams) (Link, error) {
	row := q.db.QueryRow(ctx, setLinkActive, arg.IsActive, arg.PublicID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteLink = `-- name: SoftDeleteLink :one
UPDATE
  links
SET
  deleted_at = now(),
  updated_at = now()
WHERE
  public_id = $1
  AND user_id = $2
  AND deleted_at IS NULL RETURNING id
`

type SoftDeleteLinkParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteLink, arg.PublicID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateLinkMetadata = `-- name: UpdateLinkMetadata :one
UPDATE
  links
SET
  title = $1,
  expires_at = $2,
  updated_at = now()
WHERE
  public_id = $3
  AND user_id = $4
  AND deleted_at IS NULL RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type UpdateLinkMetadataParams struct {
	Title     pgtype.Text        `json:"title"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int64              `json:"user_id"`
}

func (q *Queries) UpdateLinkMetadata(ctx context.Context, arg UpdateLinkMetadataParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkMetadata,
		arg.Title,
		arg.ExpiresAt,
		arg.PublicID,
		arg.UserID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLinkURL = `-- name: UpdateLinkURL :one
UPDATE
  links
SET
  url = $1,
  updated_at = now()
WHERE
  public_id = $2
  AND user_id = $3
  AND deleted_at IS NULL RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type UpdateLinkURLParams struct {
	Url      string      `json:"url"`
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) UpdateLinkURL(ctx context.Context, arg UpdateLinkURLParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkURL, arg.Url, arg.PublicID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLinkUrlAndHash = `-- name: UpdateLinkUrlAndHash :one
UPDATE
  links
SET
  url = $1,
  hash = $2,
  updated_at = now()
WHERE
  public_id = $3
  AND user_id = $4
  AND deleted_at IS NULL RETURNING id, public_id, user_id, url, hash, title, is_active, expires_at, created_at, updated_at, deleted_at
`

type UpdateLinkUrlAndHashParams struct {
	Url      string      `json:"url"`
	Hash     string      `json:"hash"`
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) UpdateLinkUrlAndHash(ctx context.Context, arg UpdateLinkUrlAndHashParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkUrlAndHash,
		arg.Url,
		arg.Hash,
		arg.PublicID,
		arg.UserID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Url,
		&i.Hash,
		&i.Title,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
