// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	GetLinkByHash(ctx context.Context, hash string) (Link, error)
	GetLinkByID(ctx context.Context, id int64) (Link, error)
	HardDeleteLink(ctx context.Context, id int64) (int64, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	RestoreLink(ctx context.Context, id int64) (int64, error)
	SoftDeleteLink(ctx context.Context, id int64) (int64, error)
	UpdateLinkURL(ctx context.Context, arg UpdateLinkURLParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
