// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at,
    created_ip,
    user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, family_id, user_id, token_hash, parent_id, created_at, expires_at, used_at, revoked_at, revoked_reason, created_ip, last_used_ip, user_agent
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedIp,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.LastUsedIp,
		&i.UserAgent,
	)
	return i, err
}

const createRotatedRefreshToken = `-- name: CreateRotatedRefreshToken :one
INSERT INTO refresh_tokens (
    family_id,
    user_id,
    token_hash,
    parent_id,
    expires_at,
    created_ip,
    user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, family_id, user_id, token_hash, parent_id, created_at, expires_at, used_at, revoked_at, revoked_reason, created_ip, last_used_ip, user_agent
`

type CreateRotatedRefreshTokenParams struct {
	FamilyID  pgtype.UUID        `json:"family_id"`
	UserID    int64              `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateRotatedRefreshToken(ctx context.Context, arg CreateRotatedRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRotatedRefreshToken,
		arg.FamilyID,
		arg.UserID,
		arg.TokenHash,
		arg.ParentID,
		arg.ExpiresAt,
		arg.CreatedIp,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.LastUsedIp,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < $1
   OR revoked_at < $2
`

type DeleteExpiredRefreshTokensParams struct {
	ExpiredBefore pgtype.Timestamptz `json:"expired_before"`
	RevokedBefore pgtype.Timestamptz `json:"revoked_before"`
}

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, arg DeleteExpiredRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, arg.ExpiredBefore, arg.RevokedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, family_id, user_id, token_hash, parent_id, created_at, expires_at, used_at, revoked_at, revoked_reason, created_ip, last_used_ip, user_agent
FROM refresh_tokens
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.LastUsedIp,
		&i.UserAgent,
	)
	return i, err
}

const listActiveUserRefreshSessions = `-- name: ListActiveUserRefreshSessions :many
SELECT DISTINCT ON (family_id)
    id,
    family_id,
    user_id,
    parent_id,
    created_at,
    expires_at,
    last_used_ip,
    created_ip,
    user_agent
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY family_id, created_at DESC
`

type ListActiveUserRefreshSessionsRow struct {
	ID         pgtype.UUID        `json:"id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	UserID     int64              `json:"user_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedIp *netip.Addr        `json:"last_used_ip"`
	CreatedIp  *netip.Addr        `json:"created_ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
}

func (q *Queries) ListActiveUserRefreshSessions(ctx context.Context, userID int64) ([]ListActiveUserRefreshSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserRefreshSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserRefreshSessionsRow
	for rows.Next() {
		var i ListActiveUserRefreshSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.ParentID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedIp,
			&i.CreatedIp,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :one
UPDATE refresh_tokens
SET used_at = now(),
    last_used_ip = $1
WHERE id = $2
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, family_id, user_id, token_hash, parent_id, created_at, expires_at, used_at, revoked_at, revoked_reason, created_ip, last_used_ip, user_agent
`

type MarkRefreshTokenUsedParams struct {
	LastUsedIp *netip.Addr `json:"last_used_ip"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, markRefreshTokenUsed, arg.LastUsedIp, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.LastUsedIp,
		&i.UserAgent,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now()),
    revoked_reason = COALESCE(revoked_reason, $1)
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllUserRefreshTokensParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	UserID        int64       `json:"user_id"`
}

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, arg.RevokedReason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now()),
    revoked_reason = COALESCE(revoked_reason, $1)
WHERE family_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	FamilyID      pgtype.UUID `json:"family_id"`
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.RevokedReason, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokenFamily = `-- name: RevokeUserRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now()),
    revoked_reason = COALESCE(revoked_reason, $1)
WHERE family_id = $2
  AND user_id = $3
  AND revoked_at IS NULL
`

type RevokeUserRefreshTokenFamilyParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	FamilyID      pgtype.UUID `json:"family_id"`
	UserID        int64       `json:"user_id"`
}

func (q *Queries) RevokeUserRefreshTokenFamily(ctx context.Context, arg RevokeUserRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokenFamily, arg.RevokedReason, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
