// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (email, display_name, password_hash)
VALUES
  (
    $1,
    $2,
    $3
  ) RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserWithoutPassword = `-- name: CreateUserWithoutPassword :one
INSERT INTO
  users (
    email,
    display_name,
    email_verified_at
  )
VALUES
  (
    $1,
    $2,
    $3
  ) RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserWithoutPasswordParams struct {
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) CreateUserWithoutPassword(ctx context.Context, arg CreateUserWithoutPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithoutPassword, arg.Email, arg.DisplayName, arg.EmailVerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM
  users
WHERE
  email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM
  users
WHERE
  id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT
  id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM
  users
WHERE
  public_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE
  users
SET
  email_verified_at = COALESCE(email_verified_at, now()),
  updated_at = now()
WHERE
  id = $1
  AND deleted_at IS NULL RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE
  users
SET
  status = 'blocked',
  deleted_at = now(),
  updated_at = now()
WHERE
  id = $1
  AND deleted_at IS NULL RETURNING id
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE
  users
SET
  last_login_at = now(),
  updated_at = now()
WHERE
  id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE
  users
SET
  password_hash = $1,
  updated_at = now()
WHERE
  id = $2
  AND deleted_at IS NULL RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserPasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE
  users
SET
  display_name = $1,
  updated_at = now()
WHERE
  id = $2
  AND deleted_at IS NULL RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	DisplayName string `json:"display_name"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE
  users
SET
  role = $1,
  updated_at = now()
WHERE
  public_id = $2
  AND deleted_at IS NULL RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserRoleParams struct {
	Role     string      `json:"role"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.PublicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE
  users
SET
  status = $1,
  updated_at = now()
WHERE
  public_id = $2
  AND deleted_at IS NULL RETURNING id, public_id, email, display_name, password_hash, role, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserStatusParams struct {
	Status   string      `json:"status"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.PublicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
