services:
  postgres:
    image: postgres:18.4
    container_name: postgres_go
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "${POSTGRES_DATA_PATH}:/var/lib/postgresql"
    ports:
      - "5400:5432"
